.\" Manpage for theli.
.\" Contact schirmer@mpia.de to correct errors or typos.
.TH theli 1 "May 2020" "theli 3.0.0" "theli man page"
.SH NAME
theli \- A pipeline for astronomical image data reduction
.SH SYNOPSIS
.B theli
.SH DESCRIPTION
A pipeline for astronomical image data reduction.
See https://github.com/schirmermischa/THELI for more details.
.SH OPTIONS
No options.
.SH REPORTING BUGS
Report bugs to <schirmer@mpia.de> or to the github repository
.SH AUTHOR
Mischa Schirmer (schirmer@mpia.de)
